feat: P4ADEV-449-api-create-service
pagopa/p4pa-io-notification pull request #12
Opened 2024-06-18 07:12 UTC by LarissaASLeite

#### Description

#### List of Changes
- API create service

#### Motivation and Context

#### How Has This Been Tested?

- Pre-Deploy Test
    - [x] Unit
    - [ ] Integration (Narrow)
- Post-Deploy Test
    - [ ] Isolated Microservice
    - [ ] Broader Integration
    - [ ] Acceptance
    - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [ ] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-18 08:34 UTC, antonioT90 requested changes

2024-06-18 08:34 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/repository/IOServiceRepositoryExtImpl.java
> +                        .set(Fields.organizationName, service.getOrganizationName())
this should all be setOnInsert

2024-06-18 08:34 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/IONotificationServiceImpl.java
> +        createNewService(serviceRequestDTO, service);
it's better an if/else construct instead of a if with a return inside

2024-06-18 12:27 UTC, antonioT90 approved these changes

2024-06-18 14:51 UTC, antonioT90 requested changes

2024-06-18 14:51 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IODuplicateServiceHandlerServiceImpl.java
> +    public String handleDuplicateService(IOService service, ServiceRequestDTO serviceRequestDTO) {
The scope of this Service is not more the handling of the duplicate service, but just a search operation, let's rename the class and the method
```suggestion
    public String searchIOService(IOService service, ServiceRequestDTO serviceRequestDTO) {
```

2024-06-18 14:51 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IODuplicateServiceHandlerServiceImpl.java
> +        log.info("Service request already exists, call IO to see if Service exists");
let's log also the detail about the request

2024-06-18 14:51 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
> +        log.info("Save request of Service creation");
let's log also info about the request

2024-06-18 14:51 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
> +        log.info("Creating new service from IO");
let's log also info about the request

2024-06-18 15:19 UTC, antonioT90 requested changes

2024-06-18 15:19 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
> +        }
you are logging twice! here and inside the createService method

2024-06-18 15:31 UTC, antonioT90 approved these changes

2024-06-18 15:32 UTC, merged

2024-06-19 13:26 UTC, LarissaASLeite commented on src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceImpl.java
> +    public String searchIOService(IOService service, ServiceRequestDTO serviceRequestDTO) {
I'm gonna open a fix PR for this.
Thank you!